name: CD Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Fly.io Registry
        uses: superfly/flyctl-actions@1.4
        with:
          args: "auth docker"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/backend
          push: true
          tags: registry.fly.io/reflex-backend:latest
          cache-from: type=registry,ref=registry.fly.io/reflex-backend:buildcache
          cache-to: type=registry,ref=registry.fly.io/reflex-backend:buildcache,mode=max

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.4
        with:
          args: "deploy --image registry.fly.io/reflex-backend:latest"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 