name: CD Backend (Render)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

# The Docker image is built, tested, and pushed in CI. Render should be configured to pull
# ghcr.io/${{ github.repository_owner.toLowerCase() }}/reflex-backend:${{ github.sha }} as the image for deployment.
# See: https://render.com/docs/deploy-hooks

  # Render.com deploys automatically on push to main if connected to GitHub.
  # If you want to trigger a manual deploy, uncomment and set your deploy hook below:
  #
  # - name: Trigger Render Deploy
  #   run: |
  #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
  #
  # See: https://render.com/docs/deploy-hooks
  # --- 