name: CD Backend (Render)

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (for CI only)
        uses: docker/build-push-action@v4
        with:
          context: ./apps/backend
          push: false
          tags: reflex-backend:ci

      - name: Run backend tests
        run: |
          docker run --rm \
            -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            -e SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
            -e SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} \
            reflex-backend:ci pytest

      # ---
      # Render.com deploys automatically on push to main if connected to GitHub.
      # If you want to trigger a manual deploy, uncomment and set your deploy hook below:
      #
      # - name: Trigger Render Deploy
      #   run: |
      #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      #
      # See: https://render.com/docs/deploy-hooks
      # --- 