name: CI Backend

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/backend
          push: false
          tags: ghcr.io/${{ github.repository_owner.toLowerCase() }}/reflex-backend:${{ github.sha }}
          load: true

      - name: Run backend tests in Docker image
        run: |
          docker run --rm \
            -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            -e SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
            -e SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} \
            ghcr.io/${{ github.repository_owner.toLowerCase() }}/reflex-backend:${{ github.sha }} pytest

      - name: Push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./apps/backend
          push: true
          tags: ghcr.io/${{ github.repository_owner.toLowerCase() }}/reflex-backend:${{ github.sha }}